version: "3.4"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/14 #/data
    networks:
      - app-net
    ports:
      - "5430:5432"

  api:
    build:
      context: ./backend
    container_name: api
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app-net

  nginx:
    build: ./frontend
    container_name: nginx
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
